# Generated by Django 5.0.6 on 2024-05-19 16:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('USR', 'User'), ('CMP', 'Company')], max_length=40)),
                ('address', models.CharField(max_length=42, unique=True, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$')], verbose_name='Base Wallet Address')),
            ],
        ),
        migrations.CreateModel(
            name='Oint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_address', models.CharField(max_length=42, unique=True, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$')], verbose_name='Oint Contract Address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ointmanager.company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ointmanager.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ointmanager.wallet'),
        ),
    ]
