# Generated by Django 5.0.6 on 2024-06-29 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ointmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
